# Generated by Django 4.2.30 on 2026-06-16 08:52

from django.db import migrations, models
import django.db.models.deletion
import xrays.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_local', models.ImageField(blank=True, upload_to=xrays.models.xray_upload_path)),
                ('image_cloud', models.URLField(blank=True)),
                ('storage_type', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud'), ('both', 'Both')], default='local', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('auto', 'Auto Import')], default='manual', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrays', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
