# Generated by Django 5.2.15 on 2026-09-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('xrays', '0002_xray_cloud_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xrays', to='clinics.clinic'),
        ),
    ]
