# Generated by Django 5.2.15 on 2026-09-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_clinic_invoice_clinic_and_more'),
        ('clinics', '0003_audit_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='clinics.clinic'),
        ),
    ]
