"""
Django settings for dental_clinic project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True').strip().lower() in {
    '1', 'true', 'yes', 'on', 'debug', 'development',
}

# Local setup gets a disposable key; production still fails closed without one.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-development-only' if DEBUG else None,
)

ALLOWED_HOSTS = [
    host.strip()
    for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.app.github.dev').split(',')
    if host.strip()
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'django_filters',
    # Your apps — ORDER MATTERS: accounts first
    'accounts',
    'patients',
    'appointments.apps.AppointmentsConfig',
    'xrays',
    'cloudinary',
    'cloudinary_storage',
]

import cloudinary
from urllib.parse import urlparse, unquote

cloudinary_cloud_name = config('CLOUDINARY_CLOUD_NAME', default='').strip()
cloudinary_api_key = config('CLOUDINARY_API_KEY', default='').strip()
cloudinary_api_secret = config('CLOUDINARY_API_SECRET', default='').strip()
cloudinary_url = config('CLOUDINARY_URL', default='').strip()

# Render/Cloudinary integrations sometimes provide one CLOUDINARY_URL instead
# of three separate variables. Support both formats.
if cloudinary_url and not all((
    cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret,
)):
    parsed_cloudinary_url = urlparse(cloudinary_url)
    cloudinary_cloud_name = parsed_cloudinary_url.hostname or ''
    cloudinary_api_key = unquote(parsed_cloudinary_url.username or '')
    cloudinary_api_secret = unquote(parsed_cloudinary_url.password or '')

cloudinary.config(
    cloud_name=cloudinary_cloud_name,
    api_key=cloudinary_api_key,
    api_secret=cloudinary_api_secret,
)

# Configured Cloudinary credentials imply persistent media storage. Do not tie
# this to DEBUG: a misconfigured deployment must not silently use ephemeral disk.
cloudinary_is_configured = all((
    cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret,
))
XRAY_CLOUD_UPLOAD_ENABLED = config(
    'XRAY_CLOUD_UPLOAD_ENABLED',
    default='True' if cloudinary_is_configured else 'False',
).strip().lower() in {'1', 'true', 'yes', 'on'}

# Media storage — local by default, cloud when needed
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}  # local
# Switch to this when you want cloud:
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


AUTH_USER_MODEL = 'accounts.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # all endpoints protected by default
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}


# Media files (for x-ray images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dental_clinic.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dental_clinic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_url = config('DATABASE_URL', default='sqlite:///db.sqlite3')
if database_url.startswith('sqlite:///'):
    sqlite_name = database_url[len('sqlite:///'):]
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / sqlite_name,
        }
    }
else:
    import dj_database_url
    DATABASES = {'default': dj_database_url.parse(database_url, conn_max_age=600)}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

CSRF_TRUSTED_ORIGINS = [
    'https://*.app.github.dev',
    'https://*.githubpreview.dev',
    'https://localhost:8000',
    'http://localhost:8000',
]

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
