"""
Django settings for dental_clinic project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True').strip().lower() in {
    '1', 'true', 'yes', 'on', 'debug', 'development',
}

# Silk is deliberately opt-in. Never expose a profiler containing SQL and
# request data on a public deployment.
ENABLE_SILK = config('ENABLE_SILK', default='False').strip().lower() in {
    '1', 'true', 'yes', 'on',
}

# Local setup gets a disposable key; production still fails closed without one.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-development-only' if DEBUG else None,
)

ALLOWED_HOSTS = [
    host.strip()
    for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,.app.github.dev').split(',')
    if host.strip()
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    # Your apps — ORDER MATTERS: accounts first
    'accounts',
    'patients',
    'appointments.apps.AppointmentsConfig',
    'xrays',
    'cloudinary',
    'cloudinary_storage',
]

if ENABLE_SILK:
    INSTALLED_APPS.append('silk')

import cloudinary
from urllib.parse import urlparse, unquote

cloudinary_cloud_name = config('CLOUDINARY_CLOUD_NAME', default='').strip()
cloudinary_api_key = config('CLOUDINARY_API_KEY', default='').strip()
cloudinary_api_secret = config('CLOUDINARY_API_SECRET', default='').strip()
cloudinary_url = config('CLOUDINARY_URL', default='').strip()

# Render/Cloudinary integrations sometimes provide one CLOUDINARY_URL instead
# of three separate variables. Support both formats.
if cloudinary_url and not all((
    cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret,
)):
    parsed_cloudinary_url = urlparse(cloudinary_url)
    cloudinary_cloud_name = parsed_cloudinary_url.hostname or ''
    cloudinary_api_key = unquote(parsed_cloudinary_url.username or '')
    cloudinary_api_secret = unquote(parsed_cloudinary_url.password or '')

cloudinary.config(
    cloud_name=cloudinary_cloud_name,
    api_key=cloudinary_api_key,
    api_secret=cloudinary_api_secret,
)

# Configured Cloudinary credentials imply persistent media storage. Do not tie
# this to DEBUG: a misconfigured deployment must not silently use ephemeral disk.
cloudinary_is_configured = all((
    cloudinary_cloud_name, cloudinary_api_key, cloudinary_api_secret,
))
XRAY_CLOUD_UPLOAD_ENABLED = config(
    'XRAY_CLOUD_UPLOAD_ENABLED',
    default='True' if cloudinary_is_configured else 'False',
).strip().lower() in {'1', 'true', 'yes', 'on'}
XRAY_MAX_UPLOAD_SIZE = config('XRAY_MAX_UPLOAD_SIZE_MB', default=10, cast=int) * 1024 * 1024
XRAY_MAX_IMAGE_PIXELS = config('XRAY_MAX_IMAGE_PIXELS', default=25_000_000, cast=int)
XRAY_ALLOWED_CONTENT_TYPES = ('image/jpeg', 'image/png')

# Media storage — local by default, cloud when needed
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}  # local
# Switch to this when you want cloud:
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


AUTH_USER_MODEL = 'accounts.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # all endpoints protected by default
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
        'token_refresh': '20/minute',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=8),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    # Include a password-hash claim so password changes revoke old access tokens.
    'CHECK_REVOKE_TOKEN': True,
}


# Media files (for x-ray images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'dental_clinic.middleware.LoadBalancerHealthCheckMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ENABLE_SILK:
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

    # Require a Django staff session even on a local environment. Silk records
    # request paths, timings, and SQL, so its dashboard is sensitive.
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    SILKY_PERMISSIONS = lambda user: user.is_staff
    LOGIN_URL = '/admin/login/'
    SILKY_META = True
    SILKY_MAX_RECORDED_REQUESTS = 1000
    SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10

ROOT_URLCONF = 'dental_clinic.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dental_clinic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def get_database_config():
    """Build one database configuration from the available environment.

    Hosting platforms commonly provide DATABASE_URL, while Docker Compose is
    easier to read and maintain with separate DB_* variables. A URL takes
    precedence when both styles are present. With neither style configured,
    local development falls back to a project-local SQLite database.
    """
    database_url = config('DATABASE_URL', default='').strip()

    if database_url:
        if database_url.startswith('sqlite:///'):
            sqlite_name = database_url[len('sqlite:///'):]
            sqlite_path = Path(sqlite_name)
            if not sqlite_path.is_absolute():
                sqlite_path = BASE_DIR / sqlite_path
            return {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': sqlite_path,
                }
            }

        import dj_database_url
        database = dj_database_url.parse(database_url, conn_max_age=600)
        database['CONN_HEALTH_CHECKS'] = True
        return {'default': database}

    db_host = config('DB_HOST', default='').strip()
    if db_host:
        db_secret_arn = config('DB_SECRET_ARN', default='').strip()
        return {
            'default': {
                'ENGINE': (
                    'dental_clinic.db_backends.secrets_manager_postgresql'
                    if db_secret_arn
                    else 'django.db.backends.postgresql'
                ),
                'NAME': config('DB_NAME'),
                'USER': config('DB_USER', default=''),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'HOST': db_host,
                'PORT': config('DB_PORT', default='5432'),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
                'OPTIONS': (
                    {'rds_secret_arn': db_secret_arn}
                    if db_secret_arn
                    else {}
                ),
            }
        }

    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


DATABASES = get_database_config()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

CSRF_TRUSTED_ORIGINS = [
    'https://*.app.github.dev',
    'https://*.githubpreview.dev',
    'https://localhost:8000',
    'http://localhost:8000',
]

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
