# Generated by Django 5.2.15 on 2026-09-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_audit_ownership'),
        ('patients', '0002_patientprofile_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='clinics.clinic'),
        ),
    ]
